language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install

script: bin/phpunit tests/AllTests.php

install:
  - composer self-update
  - wget https://scrutinizer-ci.com/ocular.phar

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
